apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: letterbox
  name: letterbox-loadbalancer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: letterbox
  type: LoadBalancer
