apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: letterbox-db-svc
  name: letterbox-db-svc
  namespace: letterbox
spec:
  ports:
  - name: "mysql"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: letterbox-db
  type: ClusterIP
status:
  loadBalancer: {}
